---
- name: "RouterOS: Add or set {{ ros_path }}"
  routeros_command:
    commands:
      - '{{ lookup("template", "routeros.j2") }}'
  vars:
  register: ros
  failed_when:
  - >
    (ros.stdout_lines | default([[]]))[0]
          | reject('search', '^[</:]|^$| already | with such name exists$|^changed$|^added$|^removed$')
          | join('\n')
          | list
          | length > 0
  ignore_errors: '{{ ros_ignore_errors | default(False) }}'
  changed_when:
  - '"stdout_lines" in ros and ("changed" in ros.stdout_lines[0] or "added" in ros.stdout_lines[0])'
